**NumPy**

In [1]:
import numpy as np

In [6]:
data = np.arange(12).reshape(3,4)
print(data,type(data),sep = "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>


左闭右开0-12，维度为三行四列

In [8]:
data.ndim

2

返回数组的维度数量

In [9]:
data.shape

(3, 4)

返回数组的维度大小的元组

In [10]:
data.size

12

返回数组中元素的数量

In [37]:
data.astype("float64")

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
data.astype(str)

array([['0', '1', '2', '3'],
       ['4', '5', '6', '7'],
       ['8', '9', '10', '11']], dtype='<U11')

转换数组的数据类型

In [11]:
data.dtype

dtype('int32')

返回数组数据类型
int32 和 float64 是NumPy库自己的数据类型


In [15]:
a = data.shape
b,c = a
print(type(a))
print(a)
print(b,c,sep = "\n")

<class 'tuple'>
(3, 4)
3
4


**创建NumPy数组**

In [17]:
import numpy as np

In [20]:
data1 = np.array([1,2,3])

In [ ]:
data1

array([1, 2, 3])

In [ ]:
data2

In [28]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [31]:
np.array([1,2,3,4],float)

array([1., 2., 3., 4.])

In [34]:
np.ones((4,4),dtype = 'float64')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '